title: PyTennessee 2019
email: organizers@pytennessee.org
short_name: PyTennessee

baseurl: ""
url: "https://www.pytennessee.org"
twitter_username: pytennessee

timezone: America/Chicago

permalink: pretty

collections:
  sponsors:
    output: false
  talks:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - pytn-2019.iml
  - README.md
  - scripts

visible:
  sponsors: true
  speaking: false
  speakers: true
  schedule: true
